import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/menu/general";
import Header from "./components/header/header";
import Footer from "./components/footer/footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Gestión de Bolsas Salesianos",
  //description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={`flex flex-col min-h-screen ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header/>
        <Sidebar/>
        {children}
        <div className="flex-grow"></div>
        <footer>
          <Footer></Footer>
        </footer>
      </body>
    </html>
  );
}
