SELECT Titulo, FECHAPUBLICACION FROM videoclub.Peliculas
ORDER BY TITULO DESC;

SELECT titulo, FECHAPUBLICACION, NOMBREGENERO FROM videoclub.Peliculas AS A
JOIN videoclub.Generos AS B ON A.GENERO = B.CODIGOGENERO
ORDER BY FECHAPUBLICACION ASC, GENERO DESC;

SELECT titulo, fechapublicacion, nombreGenero, modalidad FROM videoclub.Peliculas AS A
JOIN videoclub.Generos AS B ON A.GENERO = B.CODIGOGENERO
JOIN videoclub.Tipopeliculas AS C ON A.TIPOPELICULA = C.CODIGOENTREGA
ORDER BY tipopelicula, titulo ASC;

SELECT titulo, FECHAPUBLICACION, NOMBREGENERO FROM videoclub.Peliculas AS A
JOIN videoclub.Generos AS B ON A.GENERO = B.CODIGOGENERO
WHERE B.NOMBREGENERO = "Comedia"
ORDER BY A.TITULO DESC LIMIT 7;

SELECT A.*, NOMBREGENERO FROM videoclub.Peliculas AS A
JOIN videoclub.Generos AS B ON A.GENERO = B.CODIGOGENERO
WHERE B.NOMBREGENERO IN ("Drama", "Comedia")
ORDER BY B.NOMBREGENERO;

SELECT * FROM videoclub.Peliculas AS A
WHERE precio IN (15, 16)
ORDER BY titulo;

SELECT * FROM videoclub.Peliculas AS A
WHERE YEAR (FECHAPUBLICACION) = 2017;

SELECT * FROM videoclub.Peliculas
WHERE YEAR(fechapublicacion) = 2017 AND MONTH(fechapublicacion) = 7;

SELECT A.TITULO, if(B.nombregenero="infantil", "PARA NIÑOS", "PARA ADULTOS") AS RECOMENDADA FROM videoclub.Peliculas AS A
JOIN videoclub.Generos AS B ON A.GENERO = B.CODIGOGENERO;

SELECT titulo FROM videoclub.Peliculas
WHERE titulo LIKE "M%" OR titulo LIKE"P%";

SELECT titulo FROM videoclub.Peliculas
WHERE titulo LIKE "%S";

SELECT titulo FROM videoclub.Peliculas
WHERE TITULO LIKE "%AMOR%";

SELECT titulo, NOMBREGENERO FROM videoclub.Peliculas AS A
JOIN videoclub.Generos AS B ON B.CODIGOGENERO = A.GENERO
WHERE LENGTH(TITULO) = 4;

SELECT TITULO, NOMBREGENERO FROM videoclub.Peliculas AS A
JOIN videoclub.Generos AS B ON A.GENERO = B.CODIGOGENERO
WHERE LENGTH(TITULO) = 4 AND NOMBREGENERO = "ACCIÓN";

SELECT titulo FROM videoclub.Peliculas AS A
WHERE titulo REGEXP "[0-9]";

SELECT TITULO, FECHAPUBLICACION FROM videoclub.Peliculas AS A
WHERE TITULO LIKE "C%" OR TITULO LIKE "D%" OR TITULO LIKE"E%" OR TITULO LIKE "F%" OR TITULO LIKE "G%" OR TITULO LIKE"%H";

SELECT TITULO, FECHAPUBLICACION FROM videoclub.Peliculas AS A
WHERE titulo REGEXP '^[CDEFGHPQRSTUV]';

SELECT TITULO, FECHAPUBLICACION FROM videoclub.Peliculas
WHERE titulo NOT REGEXP '[I-P]$';

SELECT TITULO FROM videoclub.Peliculas
WHERE TITULO NOT LIKE "%A%";

SELECT TITULO, NOMBREGENERO FROM videoclub.peliculas AS A
JOIN videoclub.generos AS B ON A.codigopelicula = B.codigogenero
WHERE NOMBREGENERO LIKE "%COMEDIA%" OR NOMBREGENERO LIKE "TERROR" OR NOMBREGENERO LIKE "INFANTIL"
ORDER BY TITULO ASC;